@baseURL = http://localhost:3000
@apiURL = /api
@apiVersion = /v1
@apiContentType=application/json
###
http://localhost:3000/v1/api
### User autorize
# @name userAuth
POST {{baseURL}}{{apiVersion}}{{apiURL}}/users/login
Content-Type: {{apiContentType}}

{
    "username":"sarawutt.b",
    "password":"password"
}


### Create for users
POST {{baseURL}}{{apiVersion}}{{apiURL}}/users
Content-Type: application/json

{
    "username":"golange",
    "password":"password",
    "first_name": "Fiber",
    "last_name": "Last",
    "email": "fiber"
}
#### Variable Response
@accessToken = {{userAuth.response.body.$.access_token}}

### Get all for user infomation
GET {{baseURL}}{{apiVersion}}{{apiURL}}/users
Authorization: Bearer {{accessToken}}
#### Get for user infomation with id parameter
GET {{baseURL}}{{apiVersion}}{{apiURL}}/users/5
Authorization: Bearer {{accessToken}}
### Update for user infomation
PUT {{baseURL}}{{apiVersion}}{{apiURL}}/users/5
Content-Type: application/json
Authorization: Bearer {{accessToken}}
{
    "first_name": "Peter EDIT",
    "last_name": "Pet EDIT"
}

### Delete for user information
DELETE {{baseURL}}{{apiVersion}}{{apiURL}}/users/5

### Create Product
POST {{baseURL}}{{apiVersion}}{{apiURL}}/products
Content-Type: application/json

{
    "name": "Tata",
    "serial_number": "1235644424"
}

### Get all products
GET {{baseURL}}{{apiVersion}}{{apiURL}}/products

### Get Product 
GET {{baseURL}}{{apiVersion}}{{apiURL}}/products/1

### Edit Product 
PUT {{baseURL}}{{apiVersion}}{{apiURL}}/products/1
Content-Type: application/json

{
    "name" : "TOYOTA EDIT",
    "serial_number": "111111111"
}

### Delete Product 
DELETE {{baseURL}}{{apiVersion}}{{apiURL}}/products/1


### Create Order 
POST {{baseURL}}{{apiVersion}}{{apiURL}}/orders
Content-Type: application/json

{
    "user_id" : 11,
    "product_id" : 3
}

### Get all Order
GET {{baseURL}}{{apiVersion}}{{apiURL}}/orders

### Get Order
GET {{baseURL}}{{apiVersion}}{{apiURL}}/orders/1